language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t nani/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nani/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1b"
  app: "Finance"
  env: "Finance-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-647438919108"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "AKIAZNPS54XCIJ62DQOC"
  secret_access_key: "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"